// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Q6NnVnwd3O9bwsF910qXHprNUccvwws',
    appId: '1:174275113777:web:b2726bf52f80682782b610',
    messagingSenderId: '174275113777',
    projectId: 'travel-planner-be356',
    authDomain: 'travel-planner-be356.firebaseapp.com',
    storageBucket: 'travel-planner-be356.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZkU9e9O5a4Ads3PSTpKOfCt-uws4_FM',
    appId: '1:174275113777:android:e4df3cf4a25191b782b610',
    messagingSenderId: '174275113777',
    projectId: 'travel-planner-be356',
    storageBucket: 'travel-planner-be356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKcCpfQJkHFUpcrqI2rDj1RGb3dmmITk',
    appId: '1:174275113777:ios:ab3f35fc3f94c7fd82b610',
    messagingSenderId: '174275113777',
    projectId: 'travel-planner-be356',
    storageBucket: 'travel-planner-be356.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKcCpfQJkHFUpcrqI2rDj1RGb3dmmITk',
    appId: '1:174275113777:ios:ab3f35fc3f94c7fd82b610',
    messagingSenderId: '174275113777',
    projectId: 'travel-planner-be356',
    storageBucket: 'travel-planner-be356.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Q6NnVnwd3O9bwsF910qXHprNUccvwws',
    appId: '1:174275113777:web:eec7c400c13d596882b610',
    messagingSenderId: '174275113777',
    projectId: 'travel-planner-be356',
    authDomain: 'travel-planner-be356.firebaseapp.com',
    storageBucket: 'travel-planner-be356.firebasestorage.app',
  );
}
